### ISSUE TITLE
Error in multiplayer

### ISSUE THREAD

**Issue by Xarond1** [zetsumeishi/geoguessr-hack#2]
Addon error: 'utf-8' codec can't decode byte 0x9b in position 4: invalid start byte
Traceback (most recent call last):
  File "geohack.py", line 90, in websocket_message
    message_content = json.loads(message.content.decode())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 4: invalid start byte

**Comment by zetsumeishi** [comment]
I will take a look this week end.

**Comment by zetsumeishi** [comment]
I made an update, it should work fine.

**Comment by Xarond1** [comment]
An error occurred with third party (Nominatim) API.
Error: Service timed out
[16:50:14.022] Addon error: cannot access local variable 'location' where it is not associated with a value
Traceback (most recent call last):
  File "geohack.py", line 56, in response
    location, cache_hit = await get_location((lat, lng))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "geohack.py", line 43, in get_location
    cache[trimmed_coordinates] = location
                                 ^^^^^^^^
UnboundLocalError: cannot access local variable 'location' where it is not associated with a value

**Comment by zetsumeishi** [comment]
This is an error with the third party API that might not respond because it's offline or too many requests have been made. There's not much I can do but hide the error message. It's annoying if it fails in NMPZ or NM because you would need to reload the page in order to send a new requests if it fail on first load but there's not much I can do unless I can find something more reliable than Nominatim.
